language: java
jdk:
  - oraclejdk8

branches:
  only:
    - master

script: ant compile && ant runtests

language: python
python:
  - "2.7"
  - "2.6"

install:
  - pip install pandas

script: nosetests